#!/bin/bash

remove_containers(){
	if [[ "$1" == *"ALL"* ]]; then
		CONT_IDS=$(docker ps -qa)
	elif [[ $1 == *"EXITED"* ]]; then
		CONT_IDS=$(docker ps -q -f "status=exited")
	fi

	if [[ ! -z $CONT_IDS ]]; then
		echo "The following containers will be removed:"
		echo $CONT_IDS
	else
		echo "No containers found."
		exit 1
	fi

	read -p "Are you sure (y/n)? " -n 1 -r
	echo    # Move to a new line
	if [[ $REPLY =~ ^[Yy]$ ]]
	then
		docker rm -f $CONT_IDS
	fi	
}

remove_untagged_images(){
	docker images -a | grep "^<none>" | awk '{print $3}' | xargs docker rmi -f > /dev/null 2>&1
}

help(){
	echo "Usage: clean"
	printf "\t h, help\t\t: Show this help.\n"
	printf "\t ca, containers-all\t: Remove all containers.\n"
	printf "\t ce, containers-exited\t: Remove exited containers.\n"
	printf "\t images\t\t\t: Remove untagged images.\n"
	exit 0
}

if [[ -z $1 ]];then
	help
	exit 0
fi

case $1 in
	ca | containers-all)
		remove_containers "ALL"
		;;
	ce | containers-exited)
		remove_containers "EXITED"
		;;
	images)
		remove_untagged_images
		;;
	* | h | help)
		help
		;;
esac
