#!/bin/bash

if [[ ! -d "/workspace" ]]; then
	sudo mkdir -p /workspace
	sudo chown -R 500:core /workspace
fi

docker run -it --rm \
	-v /workspace:/workspace \
	--workdir=/workspace \
	yamaszone/vim-editor:EDITOR_VERSION \
	/bin/bash

