set background=dark
filetype plugin on
set tabstop=4
set shiftwidth=4
set ignorecase
set incsearch
syntax on
set laststatus=2
let &titleold="bash"

au Filetype python setl et ts=4 sw=4

function! SetTermTitle(title)
  let &titlestring = a:title
  if &term == "screen"
    set t_ts=^[k
    set t_fs=^[\
  endif
  if &term == "screen" || &term == "xterm"
    set title
  endif
endfunction
autocmd BufEnter * :call SetTermTitle(expand("%:t"))

